<?php


namespace app\modules\admin\controllers;


use app\base\BaseController;
use yii\helpers\Url;

class RbacController extends BaseController
{
    public function beforeAction($action)
    {
        if(\Yii::$app->user->isGuest){
            return $this->redirect(Url::to(['@admin/auth/sign-in']));
        }

        if(!\Yii::$app->rbac->canAdminActivity()){
            return $this->redirect(Url::to(['@admin/auth/sign-in']));
        }
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }
    public function actionGen()
    {
        \Yii::$app->rbac->generateRbac();
    }
}