<?php


namespace app\models;


class Stylists extends StylistsBase
{
    public $file;
    const CAT1 = 0;
    const CAT2 = 1;
    const CAT3 = 2;
    const CAT4 = 3;
    const CATEGORY = [self::CAT1=>'ТОП СТИЛИСТ',self::CAT2=>'ВЕДУЩИЙ СТИЛИСТ',self::CAT3=>'СТИЛИСТ',self::CAT4=>'УЧЕНИК СТИЛИСТА'];

    public function rules()
    {
        return array_merge([
            ['file', 'file', 'extensions' => ['jpg', 'png'], 'maxSize' => '10000000'],
            ['category_stylist', 'in', 'range' => array_keys(self::CATEGORY)],
        ], parent::rules()); // TODO: Change the autogenerated stub
    }
}